name: DEPLOY

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: DEPLOY - DEV
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p ~/srv/ubuntu

      - name: create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: ~/srv/ubuntu
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}

  deploy-prod:
    name: DEPLOY - PROD
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 'production deployment'